// ข้อความเริ่มต้นทั้งเว็บ — จัดกลุ่มตาม section
// key รูปแบบ "<section>.<name>" · label = คำอธิบายให้ admin เข้าใจ
export const CONTENT_DEFAULTS = [
  // ===== ส่วนกลาง =====
  { key: "common.brand_tagline", section: "common", label: "สโลแกนใต้โลโก้ (footer)", value: "ร้านหนังสือแสงดาว คัดหนังสือดีมาเพื่อคุณ ส่งถึงบ้านทั่วประเทศ" },
  { key: "footer.copyright", section: "common", label: "ข้อความลิขสิทธิ์ (footer)", value: "© 2026 SAENGDAO — ร้านหนังสือออนไลน์" },
  { key: "common.marquee_title", section: "common", label: "หัวข้อ section สำนักพิมพ์ (หน้าแรก)", value: "สำนักพิมพ์ที่คัดสรร" },
  { key: "common.brands_eyebrow", section: "common", label: "หัวข้อเล็ก section สำนักพิมพ์", value: "สำนักพิมพ์" },
  { key: "common.brands_subtitle", section: "common", label: "คำโปรย section สำนักพิมพ์", value: "รวมสำนักพิมพ์ชั้นนำที่เราภูมิใจนำเสนอ" },

  // ===== ตะกร้า =====
  { key: "cart.empty_title", section: "cart", label: "หัวข้อเมื่อตะกร้าว่าง", value: "ตะกร้าว่างเปล่า" },
  { key: "cart.empty_desc", section: "cart", label: "คำอธิบายเมื่อตะกร้าว่าง", value: "เลือกหนังสือที่คุณชอบกันก่อนนะ" },
  { key: "cart.empty_cta", section: "cart", label: "ปุ่มเมื่อตะกร้าว่าง", value: "เลือกซื้อหนังสือ" },

  // ===== หน้าชำระเงิน =====
  { key: "checkout.title", section: "checkout", label: "หัวข้อหน้า", value: "ชำระเงิน", order: 1 },
  { key: "checkout.shipping_heading", section: "checkout", label: "หัวข้อ: ที่อยู่จัดส่ง", value: "ที่อยู่จัดส่ง", order: 2 },
  { key: "checkout.field_name", section: "checkout", label: "ป้ายช่อง: ชื่อผู้รับ", value: "ชื่อผู้รับ", order: 3 },
  { key: "checkout.field_email", section: "checkout", label: "ป้ายช่อง: อีเมล", value: "อีเมล", order: 4 },
  { key: "checkout.field_phone", section: "checkout", label: "ป้ายช่อง: เบอร์โทร", value: "เบอร์โทรศัพท์", order: 5 },
  { key: "checkout.field_address", section: "checkout", label: "ป้ายช่อง: ที่อยู่", value: "ที่อยู่", order: 6 },
  { key: "checkout.receipt_toggle", section: "checkout", label: "ข้อความติ๊กออกใบเสร็จ", value: "ออกใบเสร็จรับเงิน / ใบกำกับภาษี", order: 7 },
  { key: "checkout.payment_heading", section: "checkout", label: "หัวข้อ: วิธีชำระเงิน", value: "วิธีชำระเงิน", order: 8 },
  { key: "checkout.payment_note", section: "checkout", label: "หมายเหตุใต้วิธีชำระเงิน", value: "* ขั้นตอนชำระเงินจริง (QR / สลิป / บัตร) จะเปิดใช้งานใน Phase 5", order: 9 },
  { key: "checkout.note_heading", section: "checkout", label: "หัวข้อ: หมายเหตุ", value: "หมายเหตุถึงร้าน", order: 10 },
  { key: "checkout.note_placeholder", section: "checkout", label: "placeholder ช่องหมายเหตุ", value: "ระบุรายละเอียดเพิ่มเติม เช่น เวลาที่สะดวกรับของ (ถ้ามี)", order: 11 },
  { key: "checkout.summary_heading", section: "checkout", label: "หัวข้อ: สรุปคำสั่งซื้อ", value: "คำสั่งซื้อ", order: 12 },
  { key: "checkout.discount_label", section: "checkout", label: "ป้าย: โค้ดส่วนลด", value: "โค้ดส่วนลด", order: 13 },
  { key: "checkout.apply_code", section: "checkout", label: "ปุ่มใช้โค้ด", value: "ใช้โค้ด", order: 14 },
  { key: "checkout.subtotal", section: "checkout", label: "ป้าย: ยอดรวมสินค้า", value: "ยอดรวมสินค้า", order: 15 },
  { key: "checkout.discount", section: "checkout", label: "ป้าย: ส่วนลด", value: "ส่วนลด", order: 16 },
  { key: "checkout.shipping_fee", section: "checkout", label: "ป้าย: ค่าจัดส่ง", value: "ค่าจัดส่ง", order: 17 },
  { key: "checkout.shipping_free", section: "checkout", label: "ค่าจัดส่ง (ฟรี)", value: "ฟรี", order: 18 },
  { key: "checkout.total", section: "checkout", label: "ป้าย: ยอดชำระ", value: "ยอดชำระ", order: 19 },
  { key: "checkout.submit", section: "checkout", label: "ปุ่มยืนยันคำสั่งซื้อ", value: "ยืนยันคำสั่งซื้อ", order: 20 },

  // ===== หน้าสินค้า (รายละเอียดหนังสือ) =====
  { key: "product.bc_home", section: "product", label: "เส้นทาง: หน้าแรก", value: "หน้าแรก", order: 1 },
  { key: "product.bc_shop", section: "product", label: "เส้นทาง: ร้านหนังสือ", value: "ร้านหนังสือ", order: 2 },
  { key: "product.by", section: "product", label: "คำนำหน้าผู้เขียน", value: "โดย", order: 3 },
  { key: "product.translated_by", section: "product", label: "คำนำหน้าผู้แปล", value: "แปลโดย", order: 4 },
  { key: "product.discount_label", section: "product", label: "ป้ายส่วนลด (นำหน้า %)", value: "ลด", order: 5 },
  { key: "product.in_stock_prefix", section: "product", label: "สถานะพร้อมส่ง", value: "พร้อมส่ง", order: 6 },
  { key: "product.unit_book", section: "product", label: "หน่วยนับ: เล่ม", value: "เล่ม", order: 7 },
  { key: "product.unit_piece", section: "product", label: "หน่วยนับตัวเลือก: ชิ้น", value: "ชิ้น", order: 8 },
  { key: "product.out_of_stock", section: "product", label: "ข้อความสินค้าหมด", value: "สินค้าหมด", order: 9 },
  { key: "product.variant_out", section: "product", label: "ตัวเลือกนี้หมด", value: "ตัวเลือกนี้สินค้าหมด", order: 10 },
  { key: "product.select_variant_hint", section: "product", label: "ให้เลือกตัวเลือกก่อน (ราคา/สต็อก)", value: "เลือกตัวเลือกเพื่อดูราคา/สต็อก", order: 11 },
  { key: "product.options_heading", section: "product", label: "หัวข้อ: ตัวเลือก", value: "ตัวเลือก", order: 12 },
  { key: "product.select_first", section: "product", label: "เตือนให้เลือกตัวเลือกก่อน", value: "กรุณาเลือกก่อน", order: 13 },
  { key: "product.add_to_cart", section: "product", label: "ปุ่มหยิบใส่ตะกร้า", value: "หยิบใส่ตะกร้า", order: 14 },
  { key: "product.buy_now", section: "product", label: "ปุ่มซื้อเลย", value: "ซื้อเลย", order: 15 },
  { key: "product.preview", section: "product", label: "ปุ่มอ่านตัวอย่าง", value: "อ่านตัวอย่าง", order: 16 },
  { key: "product.trust_shipping", section: "product", label: "การันตี: จัดส่ง", value: "จัดส่งฟรีทั่วประเทศ", order: 17 },
  { key: "product.trust_authentic", section: "product", label: "การันตี: ของแท้", value: "ของแท้ 100%", order: 18 },
  { key: "product.description_heading", section: "product", label: "หัวข้อ: รายละเอียด", value: "รายละเอียด", order: 19 },
  { key: "product.read_more", section: "product", label: "ปุ่มอ่านเพิ่ม", value: "อ่านเพิ่ม", order: 20 },
  { key: "product.read_less", section: "product", label: "ปุ่มย่อ", value: "ย่อ", order: 21 },
  { key: "product.specs_heading", section: "product", label: "หัวข้อ: ข้อมูลจำเพาะ", value: "ข้อมูลจำเพาะ", order: 22 },
  { key: "product.spec_publisher", section: "product", label: "ข้อมูลจำเพาะ: สำนักพิมพ์", value: "สำนักพิมพ์", order: 23 },
  { key: "product.spec_edition", section: "product", label: "ข้อมูลจำเพาะ: พิมพ์ครั้งที่", value: "พิมพ์ครั้งที่", order: 24 },
  { key: "product.spec_pages", section: "product", label: "ข้อมูลจำเพาะ: จำนวนหน้า", value: "จำนวนหน้า", order: 25 },
  { key: "product.unit_page", section: "product", label: "หน่วยนับ: หน้า", value: "หน้า", order: 26 },
  { key: "product.spec_dimensions", section: "product", label: "ข้อมูลจำเพาะ: ขนาด", value: "ขนาด", order: 27 },
  { key: "product.spec_weight", section: "product", label: "ข้อมูลจำเพาะ: น้ำหนัก", value: "น้ำหนัก", order: 28 },
  { key: "product.spec_paper", section: "product", label: "ข้อมูลจำเพาะ: กระดาษเนื้อใน", value: "กระดาษเนื้อใน", order: 29 },
  { key: "product.spec_cover", section: "product", label: "ข้อมูลจำเพาะ: ปก", value: "ปก", order: 30 },
  { key: "product.spec_isbn", section: "product", label: "ข้อมูลจำเพาะ: ISBN", value: "ISBN", order: 31 },
  { key: "product.related_eyebrow", section: "product", label: "หัวข้อเล็ก: เล่มใกล้เคียง", value: "เล่มใกล้เคียง", order: 32 },
  { key: "product.related_heading", section: "product", label: "หัวข้อ: คุณอาจสนใจ", value: "คุณอาจสนใจ", order: 33 },
  { key: "product.not_found", section: "product", label: "ข้อความไม่พบหนังสือ", value: "ไม่พบหนังสือเล่มนี้", order: 34 },
  { key: "product.back_to_shop", section: "product", label: "ปุ่มกลับไปร้านหนังสือ", value: "กลับไปร้านหนังสือ", order: 35 },

  // ===== หน้าติดต่อ =====
  { key: "contact.eyebrow", section: "contact", label: "หัวข้อเล็ก", value: "ติดต่อเรา", order: 1 },
  { key: "contact.heading", section: "contact", label: "หัวข้อใหญ่", value: "ยินดีให้บริการ", order: 2 },
  { key: "contact.subtitle", section: "contact", label: "คำโปรย", value: "มีคำถามเรื่องหนังสือ คำสั่งซื้อ หรือการจัดส่ง? ทักมาได้เลย เราตอบทุกข้อความ", order: 3 },
  { key: "contact.form_heading", section: "contact", label: "หัวข้อฟอร์ม", value: "ส่งข้อความถึงเรา", order: 4 },
  { key: "contact.form_desc", section: "contact", label: "คำอธิบายใต้หัวข้อฟอร์ม", value: "กรอกข้อความ เดี๋ยวเราติดต่อกลับโดยเร็ว", order: 5 },
  { key: "contact.form_name", section: "contact", label: "ป้ายช่อง: ชื่อ", value: "ชื่อ", order: 6 },
  { key: "contact.form_email", section: "contact", label: "ป้ายช่อง: อีเมล", value: "อีเมล", order: 7 },
  { key: "contact.form_message", section: "contact", label: "ป้ายช่อง: ข้อความ", value: "ข้อความ", order: 8 },
  { key: "contact.form_submit", section: "contact", label: "ปุ่มส่ง", value: "ส่งข้อความ", order: 9 },
];

// ชื่อ section ที่โชว์ในหลังบ้าน
export const SECTION_LABELS = {
  common: "ส่วนกลาง (โลโก้/Footer)",
  cart: "ตะกร้าสินค้า",
  checkout: "หน้าชำระเงิน",
  product: "หน้าสินค้า",
  contact: "หน้าติดต่อ",
};
